# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9245b3af044f843540f65b7da58b6dca"
name = "AeroChat-v3"
application_url = "https://shopify-v3.onrender.com"
embedded = false

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://shopify-v3.onrender.com/oauth/callback" ]
