# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9245b3af044f843540f65b7da58b6dca"
name = "AeroChat-v3"
application_url = "https://aerochat-v1.onrender.com"
embedded = false

[webhooks]
api_version = "2025-07"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request"]
uri = "https://aerochat-v1.onrender.com/webhooks/customers/data_request"

[[webhooks.subscriptions]]
compliance_topics = ["customers/redact"]
uri = "https://aerochat-v1.onrender.com/webhooks/customers/redact"

[[webhooks.subscriptions]]
compliance_topics = ["shop/redact"]
uri = "https://aerochat-v1.onrender.com/webhooks/shop/redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://aerochat-v1.onrender.com/oauth/callback" ]
